# Generated by Django 4.2.4 on 2023-10-18 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaVocacional', '0007_alter_test_id_estudiante'),
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='id_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PruebaVocacional.student', verbose_name='ID de estudiante'),
        ),
    ]
