# Generated by Django 4.2.4 on 2023-10-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaVocacional', '0007_alter_test_id_estudiante'),
        ('herramientas', '0002_clase_id_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nota', models.FloatField()),
                ('creditos', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PruebaVocacional.student')),
            ],
        ),
    ]
