# Generated by Django 4.2.4 on 2023-11-04 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herramientas', '0003_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='id_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID de estudiante'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
