# Generated by Django 4.2.4 on 2023-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_completo', models.CharField(max_length=25)),
                ('Edad', models.PositiveSmallIntegerField()),
                ('categorias_ocupacionales', models.CharField(max_length=50)),
                ('materias', models.CharField(max_length=50)),
                ('competencia_profesionales', models.CharField(max_length=50)),
                ('valores_ocupacionales', models.CharField(max_length=50)),
                ('inventario_intereses', models.CharField(max_length=50)),
            ],
        ),
    ]
