# Generated by Django 4.2.4 on 2023-09-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaVocacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('nombre', models.CharField(max_length=25)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.FileField(upload_to='answers')),
            ],
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
