# Generated by Django 4.2.4 on 2023-09-13 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaVocacional', '0003_rename_id_test_id_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='id_estudiante',
        ),
        migrations.AddField(
            model_name='test',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='id_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PruebaVocacional.student', verbose_name='ID de estudiante'),
        ),
    ]
