# Generated by Django 4.2.4 on 2023-09-13 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaVocacional', '0007_alter_test_id_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PruebaVocacional.student', verbose_name='ID de estudiante'),
        ),
    ]
