# Generated by Django 4.2.4 on 2023-09-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaVocacional', '0002_student_alter_test_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='id',
            new_name='id_estudiante',
        ),
    ]
