# Generated by Django 4.2.4 on 2023-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('nombre', models.CharField(max_length=25)),
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('universitario', models.BooleanField(default=False)),
            ],
        ),
    ]
