# Generated by Django 4.2.4 on 2023-11-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='carrera',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
