# Generated by Django 4.2.4 on 2023-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='carrera',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
