# Generated by Django 4.2.4 on 2023-11-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_student_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='carrera',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
