# Generated by Django 4.2.4 on 2023-11-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_student_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='carrera',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
